# Generated by Django 3.0.1 on 2020-04-01 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash_block', models.CharField(max_length=200)),
                ('confirmations', models.CharField(max_length=200)),
                ('datetime', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.CharField(max_length=200)),
                ('number_txs', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=200)),
                ('bits', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('nonce', models.CharField(max_length=200)),
            ],
        ),
    ]
